apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: dejmartins/product-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PRODUCT_DB_URI
              value: mongodb+srv://username:E805tKmaZYEo0XZe@mongo-vcore-cluster.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
