apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: dejmartins/order-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: ORDER_QUEUE_URI
              value: amqp://username:password@rabbitmq:5672
            - name: ORDER_QUEUE_HOSTNAME
              value: rabbitmq
            - name: ORDER_QUEUE_USERNAME
              value: username
            - name: ORDER_QUEUE_PASSWORD
              value: password
            - name: ORDER_QUEUE_NAME
              value: orders
            - name: ORDER_DB_URI
              value: mongodb+srv://username:E805tKmaZYEo0XZe@mongo-vcore-cluster.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
            - name: ORDER_DB_NAME
              value: orderdb
            - name: ORDER_DB_COLLECTION_NAME
              value: orders
            - name: ORDER_QUEUE_PORT
              value: "5672"
            - name: ORDER_QUEUE_TRANSPORT
              value: tcp
