apiVersion: v1
kind: Service
metadata:
  name: makeline-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: makeline-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
