apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: dejmartins/store-admin:latest
          ports:
            - containerPort: 8081
