apiVersion: v1
kind: Service
metadata:
  name: store-admin
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: store-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
