apiVersion: v1
kind: Service
metadata:
  name: store-front
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: store-front
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080
